name: generate-documentation
run-name: Generate Documentation for all JS files in source
on:
  workflow_call:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          ref: fortune-telling-dev
          path: main/fortune-telling-dev
          clean: false
      - run: rm -rf main/fortune-telling-dev/.git

      - name: Build Documentation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: main/fortune-telling-dev/source
          output_dir: ./out
          template: minami
          front_page: README.md
          
      - name: Delete documentation branch
        run:
          git push origin -d documentation

      - name: Upload Docs to branch
        uses: EndBug/add-and-commit@v9
        with:
          add: './out/*'
          new_branch: documentation
